name: stellarwar

services:
  spacetime:
    image: clockworklabs/spacetimedb
    ports:
      - "3000:80"
  prometheus:
    image: prom/prometheus
    network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-oss
    network_mode: host
    environment:
      - GF_SERVER_HTTP_PORT=5000
    ports:
      - 5000:5000
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
